-- Seed faculty contacts from TAAS 2025 CSV
INSERT INTO public.faculty_contacts (faculty_name, email, updated_at)
VALUES
  ('Henry B Prudente', 'hbprudente@pup.edu.ph', NOW()),
  ('Almoncito M. Salac', 'amsalac@pup.edu.ph', NOW()),
  ('Fernando F. Estingor', 'ffestingor@pup.edu.ph', NOW()),
  ('Jenny Q. Estingor', 'jqestingor@ipup.edu.ph', NOW()),
  ('Micalyne R. Amurao', 'mramurao@pup.edu.ph', NOW()),
  ('Criselda P. Coronado', 'cpcoronado@pup.edu.ph', NOW()),
  ('May M. Galang', 'mmgalang@pup.edu.ph', NOW()),
  ('Melani L. Garcia', 'mlgarcia@pup.edu.ph', NOW()),
  ('Jomar Pineda', 'jepineda@pup.edu.ph', NOW()),
  ('Henry B. Prudente', 'hbprudente@pup.edu.ph', NOW()),
  ('Cecilia R. Alagon', 'cralagon@pup.edu.ph', NOW()),
  ('Alfred M. Pagalilawan', 'ampagalilawan@pup.edu.ph', NOW()),
  ('Jane L. Mendoza', 'jlmendoza@pup.edu.ph', NOW()),
  ('Ronette M. Espiritu', 'rmespiritu@pup.edu.ph', NOW()),
  ('Ian J. Saguindan', 'ijsaguindan@pup.edu.ph', NOW()),
  ('Lourdes R. Dela Cruz', 'lordelacruz@pup.edu.ph', NOW()),
  ('Lemuel N. Damole', 'lndamole@pup.edu.ph', NOW()),
  ('Dianne Marie V. Ingreso', NULL, NOW()),
  ('Maria Carina P. Corpuz', 'mcpcorpuz@pup.edu.ph', NOW()),
  ('Dr. Jackie D. Urrutia', 'jdurrutia@pup.edu.ph', NOW()),
  ('Dr. Mercy O. Manalo', 'momanalo@pup.edu.ph', NOW()),
  ('Mark Anecito R. Perlas', 'marperlas@pup.edu.ph', NOW()),
  ('John Amiel A. Rivera', 'jaarivera@pup.edu.ph', NOW()),
  ('Soliman A. Santos', 'sasantos@pup.edu.ph', NOW()),
  ('Dr. Dorren D. Arenque', 'ddarenque@pup.edu.ph', NOW()),
  ('Jose V. Clutario', 'jvclutario@pup.edu.ph', NOW()),
  ('Mary Joy A. Villalino', 'mjavillalino@pup.edu.ph', NOW()),
  ('Lady Valerie Ann P. Magsalin', 'ivapmagsalin@pup.edu.ph', NOW()),
  ('Erwin L. Descallar', 'eldescallar@pup.edu.ph', NOW()),
  ('Estefanie R. Cortez', 'ercortez@pup.edu.ph', NOW()),
  ('Jimp Israel S. Cabuhat', 'jiscabuhat@pup.edu.ph', NOW()),
  ('Kamille L. Torres', NULL, NOW()),
  ('Dr. Arman DC. Santos', 'adcsantos@pup.edu.ph', NOW()),
  ('Dr. Katherine Joyce M. Castro', 'kjmcastro@pup.edu.ph', NOW()),
  ('Dr. Honesto O. Camino', 'hocamino@pup.edu.ph', NOW()),
  ('Dr. Ginalyn B. Panghulan', 'gbpanghulan@pup.edu.ph', NOW()),
  ('Dr. Sherry Ann M. Bacolod', 'sacmedrano@pup.edu.ph', NOW()),
  ('David John D. Apigo', 'djdapigo@pup.edu.ph', NOW()),
  ('Dr. Leo G. Alcaraz', 'lgalcaraz@pup.edu.ph', NOW()),
  ('Mark Gregory P. Isip', 'mgpisip@pup.edu.ph', NOW()),
  ('Dr. Sanjay P. Claudio', 'spclaudio@pup.edu.ph', NOW()),
  ('Dr. Geraldine F. Santos', 'gfsantos@pup.edu.ph', NOW()),
  ('Gregorio R. Caligua III', 'grcaliguiaiii@pup.edu.ph', NOW()),
  ('Joshua Bernard B. Espena', 'jbbespena@pup.edu.ph', NOW()),
  ('Ar. Ranier L. Biglang-Awa', 'ribiglang-awa@pup.edu.ph', NOW()),
  ('Ar. Jocelyn A. Rivera-Lutap', 'jarlutap@pup.edu.ph', NOW()),
  ('Jori Lace R. Basbas', 'jlrbasbas@pup.edu.ph', NOW()),
  ('Lenin Carlos M. Mirasol', 'lcmirasol@pup.edu.ph', NOW()),
  ('Michael Anjelo O. Miguel', 'maomiguel@pup.edu.ph', NOW()),
  ('Dr. Florante D. Poso Jr.', 'fdposojr@pup.edu.ph', NOW()),
  ('Shin G. Sedenio', 'sgsedenio@pup.edu.ph', NOW()),
  ('Rhene A. Camarador', 'racamarador@pup.edu.ph', NOW()),
  ('Lisa D. Camarador', 'ldcamarador@pup.edu.ph', NOW()),
  ('Jane Claire S. Sacandal', 'jcssacandal@pup.edu.ph', NOW()),
  ('Princess Anne Mendoza', 'pamendoza@pup.edu.ph', NOW()),
  ('Myra Monina B. Dela Cruz', 'mmbdelacruz@pup.edu.ph', NOW()),
  ('EnP. Ibylou B. Golla', 'ibgolia@pup.edu.ph', NOW()),
  ('Raymund E. Mindanao', 'remindanao@pup.edu.ph', NOW()),
  ('Dr. Edison E. Mojica', 'eemojica@pup.edu.ph', NOW()),
  ('Dr. Remedios G. Ado', 'rgado@pup.edu.ph', NOW()),
  ('Dr. Maria Charlene P. Melegrito', 'mcpmelegrito@pup.edu.ph', NOW()),
  ('Dr. Christoper F. Sasot', 'cfsasot@pup.edu.ph', NOW()),
  ('Engr. Jo-Ann V. Magsumbol', 'javmagsumbol@pup.edu.ph', NOW()),
  ('John Paolo Sarce', 'jpsarce@pup.edu.ph', NOW()),
  ('Cresilda M. Bragas', 'cmbragas@pup.edu.ph', NOW()),
  ('Ma. Leila R. Aguila', 'mlraguila@pup.edu.ph', NOW()),
  ('Melanie J. Reyes', 'mmjiminez@pup.edu.ph', NOW()),
  ('Dr. Geraldine C. Minas', 'gcminas@pup.edu.ph', NOW()),
  ('Dr. Allan Calderon', 'aacalderon@pup.edu.ph', NOW()),
  ('Dr. John Mark S. Distor', 'jmsdistor@pup.edu.ph', NOW()),
  ('Dr. Ria Fajilago', 'rsfajilago@pup.edu.ph', NOW()),
  ('Dr. Ricky R. Rosales', 'rrrosales@pup.edu.ph', NOW()),
  ('Ar. Rene Francis C. Dimalanta', 'rfcdimalanta@pup.edu.ph', NOW()),
  ('Engr. Robert Michael B. Corpuz,', 'rmbcorpus@pup.edu.ph', NOW()),
  ('Engr. John Dennice Ganotisi', 'jdcganotisi@pup.edu.ph', NOW()),
  ('Engr. Peter Vasquez', 'pvasquez@pup.edu.ph', NOW()),
  ('1. Dr. Remedios G. Ado', 'rgado@pup.edu.ph', NOW()),
  ('1.Engr. Orlando V. Pajabera', 'ovpajabera@pup.edu.ph', NOW()),
  ('1. Engr. Kenneth Bryan M. Tana', 'kbmtana@pup.edu.ph', NOW()),
  ('2. Engr, Ramir M. Cruz', 'rm.cruz@pup.edu.ph', NOW()),
  ('3. Engr. Ruffa S. Roxas', NULL, NOW()),
  ('4. Engr. Edna P. Arrojado', 'eparrojado@pup.edu.ph', NOW()),
  ('5. Engr. Nhel Adrian B. Bartoline', 'nabbartoline@pup.edu.ph', NOW()),
  ('6. Engr. Joseph Raniel B. Bianes', 'jrabianes@pup.edu.ph', NOW()),
  ('7. Engr. Prospero C. Cabornay', 'pccabornay@pup.edu.ph', NOW()),
  ('9. Engr. Razon C. Domingo', 'rcdomingo@pup.edu.ph', NOW()),
  ('10. Engr. Florante D. Poso Jr.', 'fdposojr@pup.edu.ph', NOW()),
  ('11. Engr. Noli B. Sibayan', 'nbsibayan@pup.edu.ph', NOW()),
  ('12. Engr. Melvin G. Singayan', 'mgsingayan@pup.edu.ph', NOW()),
  ('1. Dr. Edison E. Mojica', 'eemojica@pup.edu.ph', NOW()),
  ('2. Engr. Benson G. Pulga', 'bgpulga@pup.edu.ph', NOW()),
  ('3. Engr. Jesus Benjamin J. Bien, Jr.', 'jbjbien@pup.edu.ph', NOW()),
  ('4. Engr. Faustino R. Rural', 'ffrural@pup.edu.ph', NOW()),
  ('5. Engr. Kevin M. Suliva', 'kmsuliva@pup.edu.ph', NOW()),
  ('6. Engr. Ram F. Fernando', 'rffernando@pup.edu.ph', NOW()),
  ('1. Engr. Robert Michael B. Corpus', 'rmbcorpus@pup.edu.ph', NOW()),
  ('2. Engr. Aldion J. Almacha', 'ajalmacha@pup.edu.ph', NOW()),
  ('3. Engr. John Dennice C. Ganotisi', 'jdcganotisi@pup.edu.ph', NOW()),
  ('4. Engr. Robel A. Nomorosa', 'ranomorosa@pup.edu.ph', NOW()),
  ('5. Mr. Jason D. Limkian', 'jdlimkian@pup.edu.ph', NOW()),
  ('1. Ms. Angelita T. Gallano', 'atgallano@pup.edu.ph', NOW()),
  ('2. Mr. Chowi Jeme I. Nario', 'cjinario@pup.edu.ph', NOW()),
  ('3. Ms. Shainalyn M. Tana', 'smtana@pup.edu.ph', NOW()),
  ('Dr. Ian I. Llenares', 'iillenares@pup.edu.ph', NOW()),
  ('Dr. Sheryl R. Morales', 'srmorales@pup.edu.ph', NOW()),
  ('Dr. Edna T. Bernabe', 'etbernabe@pup.edu.ph', NOW()),
  ('Davidson G. Oliveros', 'dgoliveros@pup.edu.ph', NOW()),
  ('Dr. Ferdie T. Lubis', 'ftlubis@pup.edu.ph', NOW()),
  ('Honey Bert G. Dayanan', 'hgdayanan@pup.edu.ph', NOW()),
  ('Dr. Angelita S. Villaruel', 'asvillaruel@pup.edu.ph', NOW()),
  ('Inst. David L. Soriano', 'dlsoriano@pup.edu.ph', NOW()),
  ('Dr. Emejido C. Gepila Jr.', 'ecgepilajr@pup.edu.ph', NOW()),
  ('Asst. Prof. Peter Glenn J. Biason', 'pgjbiason@pup.edu.ph', NOW()),
  ('Assoc. Prof. Luzviminda O. Tugade', 'lo.tugade@pup.edu.ph', NOW()),
  ('Ast. Prof. John Dahrell J. Vilela', 'jdjvilela@pup.edu.ph', NOW()),
  ('Asst. Prof. Algene M. De Guzman', 'amdeguzman@pup.edu.ph', NOW()),
  ('Instructor Genesis S. Linga', 'gslinga@pup.edu.ph', NOW()),
  ('Assistant Professor Antonio F. Enriquez, Jr.', 'afenriquezjr@pup.edu.ph', NOW()),
  ('Dr. Pricila B. Marzan', 'pbmarzan@pup.edu.ph', NOW()),
  ('Prof. Rebecca E. Palma', 'repalma@pup.edu.ph', NOW()),
  ('Catherine D. Sotto', 'cdsotto@pup.edu.ph', NOW()),
  ('Assoc. Prof. Rosemarie O. Roque', 'rroque@pup.edu.ph', NOW()),
  ('Ramces M. Dili', 'rmdili@pup.edu.ph', NOW()),
  ('Dr. Elmer M. Soriano', 'emsoriano@pup.edu.ph', NOW()),
  ('Rebecca E. Palma', 'repalma@pup.edu.ph', NOW()),
  ('Michael Pechardo', 'mspechardo@pup.edu.ph', NOW()),
  ('Patrick Rico', 'pjrrico@pup.edu.ph', NOW()),
  ('Mecmack A. Nartea', 'manartea@pup.edu.ph', NOW()),
  ('Dr. Romeo P. Pena', 'rppena@pup.edu.ph', NOW()),
  ('Maricel F. De Chavez,', 'mfdechavez@pup.edu.ph', NOW()),
  ('Leila R. Aguila', 'mlraguila@pup.edu.ph', NOW()),
  ('Dr. Angelita M. Pagcaliwagan', 'ampagcaliwagan@pup.edu.ph', NOW()),
  ('Gicel Roger B. Salvilla', 'grbsalvilla@pup.edu.ph', NOW()),
  ('Dr. Cherry D. Casuat', 'cdcasuat@pup.edu.ph', NOW()),
  ('Dr. Philip P. Ermita', 'ppermita@pup.edu.ph', NOW()),
  ('Dr. Juancho D. Espineli', 'jdespineli@pup.edu.ph', NOW()),
  ('Ryan V. Labana', 'rvlabana@pup.edu.ph', NOW()),
  ('Mary Rose Maharlika P. Cruz', 'mrmjpalmares@pup.edu.ph', NOW()),
  ('Dr. Minerva D. Ferranco', 'md.ferranco@pup.edu.ph', NOW()),
  ('Dr. Jayson Carl C. Esmasin', 'jccesmasin@pup.edu.ph', NOW()),
  ('Dr. Gregorio A. Reyes', 'gareyes@pup.edu.ph', NOW()),
  ('Dr. Robert G. de Luna', 'rgdeluna@pup.edu.ph', NOW()),
  ('Engr. Luisito L. Lacatan', 'lllacatan@pup.edu.ph', NOW()),
  ('Dr. Noel A. Saguil', 'nasaguil@pup.edu.ph', NOW()),
  ('Ar. Jocelyn A. Rivera Lutap', 'jarlutap@pup.edu.ph', NOW()),
  ('Dr. Hermina Manimtim', 'hemanimtim@pup.edu.ph', NOW()),
  ('Dr. Hemmady S. Mora', 'hs.mora@pup.edu.ph', NOW()),
  ('Dr. Noel Llenard J. Robledo', 'nljrobledo@pup.edu.ph', NOW()),
  ('Dr. Jose Reuben Q. Alagaran II', 'jrqalagaran@pup.edu.ph', NOW()),
  ('Sherry Ann Medrano-Bacolod', 'sacmedrano@pup.edu.ph', NOW()),
  ('Dr. Leilidyn Y. Zurbano', 'lyzurbano@pup.edu.ph', NOW()),
  ('Assoc. Prof. Altagracia A. Silaya', 'aasilaya@pup.edu.ph', NOW()),
  ('Asst. Prof. Lesley Ann C. Magtibay', 'lahchan@pup.edu.ph', NOW()),
  ('Asst. Prof. Anna Madonna M. Arellano', 'ammarellano@pup.edu.ph', NOW()),
  ('Assoc. Prof. Ma. Eleanor C. Salvador', 'mecsalvador@pup.edu.ph', NOW()),
  ('Dr. Joana Marie Carina M. Gabunilas', 'jmcmgabunilas@pup.edu.ph', NOW()),
  ('Dr. Annabelle A. Gordonas', 'aagordonas@pup.edu.ph', NOW()),
  ('Engr. Robert Michael B. Corpus', 'rmbcorpus@pup.edu.ph', NOW()),
  ('Johncel Tawat, CPA', 'jtawat@pup.edu.ph', NOW()),
  ('Assoc. Prof. Laurence P. Usona', 'lpusona@pup.edu.ph', NOW()),
  ('Ar. Kenji H. Roxas', 'khroxas@pup.edu.ph', NOW()),
  ('Vincent Paul R. Reyes', 'vprreyes@pup.edu.ph', NOW()),
  ('Dr. Karl Patrick R. Mendoza', 'kprmendoza@pup.edu.ph', NOW()),
  ('Asst. Prof. Davidson G. Oliveros', 'dgoliveros@pup.edu.ph', NOW()),
  ('Paul Ryan A. Longhas', 'pralonghas@pup.edu.ph', NOW()),
  ('Arch. Jocelyn Rivera- Lutap', 'jarlutap@pup.edu.ph', NOW()),
  ('Hazel DR. Samala', 'hdrsamala@pup.edu.ph', NOW()),
  ('Dr. Rafael Michael O. Paz', 'rmo.paz@pup.edu.ph', NOW()),
  ('Dr. Ria Santos Fajilago', 'rsfajilago@pup.edu.ph', NOW()),
  ('Dr. Andrea Rose E. Rimorin', 'arerimorin@pup.edu.ph', NOW()),
  ('Dr. Marvin Lascano', 'mvlascano@pup.edu.ph', NOW()),
  ('Dr. Jonathan P. Binaluyo', 'jpbinaluyo@pup.edu.ph', NOW()),
  ('Instr. Joseph Victor D. Deseo', 'jvddeseo@pup.edu.ph', NOW()),
  ('Jedidia Eunice P. Peña', 'jeppena@pup.edu.ph', NOW()),
  ('Mr. Rimando Felicia', 'refelicia@pup.edu.ph', NOW()),
  ('Mr. Eric Lazarte', 'erlazarte@pup.edu.ph', NOW()),
  ('Dr. Hilda San Gabriel', 'hfsangabriel@pup.edu.ph', NOW()),
  ('Prof. Jhonley O. Cubacub', 'jocubacub@pup.edu.ph', NOW()),
  ('Dr. Florante C. Poso Jr.', 'fdposojr@pup.edu.ph', NOW()),
  ('Jackson Jake U. Llames', 'jjullames@pup.edu.ph', NOW()),
  ('Rhenz Nicole M. Parada', 'rnmparada@pup.edu.ph', NOW()),
  ('Rommel C. Dela Cruz', 'rcdelacruz@pup.edu.ph', NOW()),
  ('Dr. Luisito L. Lacatan', 'lllacatan@pup.edu.ph', NOW()),
  ('Dr. Marivi T. Camacho', 'mtcamacho@pup.edu.ph', NOW()),
  ('Asst. Prof. Jenilyn M. Almanza', 'jmalmanza@pup.edu.ph', NOW()),
  ('Assoc. Prof. Roan Jessa A. Dino', 'rjadino@pup.edu.ph', NOW()),
  ('Ma. Ymelda C. Batalla', 'mycbatalla@pup.edu.ph', NOW()),
  ('Dr. Joana Marie C. Gabunilas', 'jmcmgabunilas@pup.edu.ph', NOW()),
  ('Christine A. Del Rosario', 'ca.delrosario@pup.edu.ph', NOW()),
  ('Jaime R. Delos Santos', 'jrdelossantos@pup.edu.ph', NOW()),
  ('Dr. Arvin R. Dela Cruz', 'arrdelacruz@pup.edu.ph', NOW()),
  ('Mark Joseph N. Rafal', 'mjnrafal@pup.edu.ph', NOW()),
  ('Dr. Rolando P. Quinones', 'rpquinones@pup.edu.ph', NOW()),
  ('Arch. Rainier L. Biglang- Awa', 'rlbiglang-awa@pup.edu.ph', NOW()),
  ('Algene M. De Guzman', 'amdeguzman@pup.edu.ph', NOW()),
  ('Dominador Acasamoso Jr.', 'dmacasamosojr@pup.edu.ph', NOW()),
  ('Dr. Marlon C. Laguerta', 'mclaguerta@pup.edu.ph', NOW()),
  ('Asst. Prof. Junephrey M. Ocampo', 'junmocampo@pup.edu.ph', NOW()),
  ('Dr. Armin S. Coronado', 'ascoronado@pup.edu.ph', NOW()),
  ('Hjelmar M. Abulencia', 'hmabulencia@pup.edu.ph', NOW()),
  ('Dr. Jo-Ann V. Magsumbol', 'javmagsumbol@pup.edu.ph', NOW()),
  ('Dr. Luisito Lolong Lacatan', 'lllacatan@pup.edu.ph', NOW()),
  ('Alexander B. Prudente', 'abprudentejr@pup.edu.ph', NOW()),
  ('Dr. Ibylou Bandala-Golla', 'ibgolla@pup.edu.ph', NOW()),
  ('Geraldine C. Miñas', 'gcminas@pup.edu.ph', NOW()),
  ('Jun C. Alave', 'jcalave@pup.edu.ph', NOW()),
  ('Joana Marie Carina M. Gabunilas', 'jmcmgabunilas@pup.edu.ph', NOW()),
  ('Ferdie T. Lubis', 'ftlubis@pup.edu.ph', NOW()),
  ('Heildenberg C. Dimarucot', 'hcdimarucot@pup.edu.ph', NOW()),
  ('Dr. Cecilia R. Alagon', 'cralagon@pup.edu.ph', NOW()),
  ('Assoc. Prof. Rimando E. Felicia', 'refelicia@pup.edu.ph', NOW()),
  ('Dr. Iluminada Vivien R. Domingo', 'ivrdomingo@pup.edu.ph', NOW()),
  ('Julie Jane S. Lara', 'jjslara@pup.edu.ph', NOW()),
  ('Rock Bryan B. Matias', 'rbbmatias@pup.edu.ph', NOW()),
  ('Octavio O. Pagalilawan', 'ompagalilawan@pup.edu.ph', NOW()),
  ('Ma. Gay M. Teopengco', 'mgmteopengco@pup.edu.ph', NOW()),
  ('Regina B. Zuñiga', 'rbzuniga@pup.edu.ph', NOW()),
  ('Dr. Marilou B. Francisco', 'mbfrancisco@pup.edu.ph', NOW()),
  ('Rowena D. Miranda', 'rdlmiranda@pup.edu.ph', NOW()),
  ('Lyza P. Pagapulan', 'lppagapulan@pup.edu.ph', NOW()),
  ('Ivy Joy Saen', 'ijrsaen@pup.edu.ph', NOW()),
  ('Arnel O. Rendon', 'aorendon@pup.edu.ph', NOW()),
  ('John Dahrell Vilela', 'jdjvilela@pup.edu.ph', NOW()),
  ('Katrina Elison', 'kdelizon@pup.edu.ph', NOW()),
  ('Alejandro Jose C. Reboa', 'ajcreboa@pup.edu.ph', NOW()),
  ('Renz S. Bareo', 'rsbareo@pup.edu.ph', NOW()),
  ('Rengie Mark Malig', 'rmdmailig@pup.edu.ph', NOW()),
  ('Sigmund Breton', 'sfbreton@pup.edu.ph', NOW()),
  ('Danielito Dollete', 'dldollete@pup.edu.ph', NOW()),
  ('Marjielou C. Abinsay', 'mcabinsay@pup.edu.ph', NOW()),
  ('Herald Sen S. Mateo', 'hssmateo@pup.edu.ph', NOW()),
  ('Leine S. Alcaraz', 'lsalcaraz@pup.edu.ph', NOW()),
  ('Dr. Emejidio C. Gepila, Jr.', 'ecgepilajr@pup.edu.ph', NOW()),
  ('Dr. Ma. Cristina Q. Trinidad', 'mcqtrinidad@pup.edu.ph', NOW()),
  ('Dr. Florante D. Poso, Jr', 'fdposojr@pup.edu.ph', NOW()),
  ('Jhonley O. Cubacub', 'jocubacub@pup.edu.ph', NOW()),
  ('Dr. Heildenberg C. Dimarucot', 'hcdimarucot@pup.edu.ph', NOW()),
  ('Edgar Allan DC. Mendoza', 'eadmendoza@pup.edu.ph', NOW()),
  ('Alyssa M. Teodoro', 'amteodoro@pup.edu.ph', NOW()),
  ('Dr. Algene M. De Guzman', 'amdeguzman@pup.edu.ph', NOW()),
  ('Asst. Prof. Aldrin Phillip C. Trance', 'aptrance@pup.edu.ph', NOW()),
  ('Alleyromae O. Indong, RCh', 'aoindong@pup.edu.ph', NOW()),
  ('Aileen Camille B. Dimatatac', 'acbdimatatac@pup.edu.ph', NOW()),
  ('Dr. Ryan C. Roque', 'rcroque@pup.edu.ph', NOW()),
  ('Dr. Florante D. Poso', 'fdposojr@pup.edu.ph', NOW()),
  ('Joshua Bernard B. España', 'jnnespena@pup.edu.ph', NOW()),
  ('Aldrin Phillip C. Trance, RCh', 'aptrance@pup.edu.ph', NOW()),
  ('Dr. Adelia R. Roadilla', 'arroadilla@pup.edu.ph', NOW()),
  ('Kim Bernard G. Fajardo', 'kbgfajardo@pup.edu.ph', NOW()),
  ('Dr. Aimee Rose A. Manda', 'aramanda@pup.edu.ph', NOW()),
  ('Dr. Benjie M. Manila', 'bmmanila@pup.edu.ph', NOW()),
  ('Dr. Emily V. Banzel', 'evbanzel@pup.edu.ph', NOW()),
  ('John Paolo C. Dalupang', 'jpcdalupang@pup.edu.ph', NOW()),
  ('Dr. Ariel Robert C. Ponce', 'arcponce@pup.edu.ph', NOW()),
  ('Hilario M. Fontanilla', 'hmfontanilla@pup.edu.ph', NOW()),
  ('Melinda F. Santos', 'mfsantos@pup.edu.ph', NOW()),
  ('Dr. Jose Reuben O. Alagaran II', 'jrqalagaran@pup.edu.ph', NOW()),
  ('Mr. Kent B. Pitero', 'kbpitero@pup.edu.ph', NOW()),
  ('Jenilyn M. Almanza', 'jmalmanza@pup.edu.ph', NOW()),
  ('Dr. Lourdes V. Alvarez', 'lvalvarez@pup.edu.ph', NOW()),
  ('Renato E. Apa-ap', 'reapa-ap@pup.edu.ph', NOW()),
  ('Dr. Sherry Ann Medrano-Bacolod', 'sacmedrano@pup.edu.ph', NOW()),
  ('Karl Patrick R. Mendoza', 'kprmendoza@pup.edu.ph', NOW()),
  ('Federico Jr. Arzadon', 'frarzadonjr@pup.edu.ph', NOW()),
  ('Jonathan P. Binaluyo', 'jpbinaluyo@pup.edu.ph', NOW()),
  ('Ruth P. Carlos', 'rpcarlos@pup.edu.ph', NOW()),
  ('Ria S. Fajilago', 'rsfajilago@pup.edu.ph', NOW()),
  ('Marvin Lascano', 'mvlascano@pup.edu.ph', NOW()),
  ('Andrea Rose E. Rimorin', 'arerimorin@pup.edu.ph', NOW()),
  ('Alyssa Mae Resurreccion', 'ammresurreccion@pup.edu.ph', NOW()),
  ('Randy D. Sagun', 'rdsagun@pup.edu.ph', NOW()),
  ('Dr. Ginno L. Andres', 'glandres@pup.edu.ph', NOW()),
  ('Symon M. Carpiso', 'smcarpiso@pup.edu.ph', NOW()),
  ('Bernadette Q. Cunanan', 'bqcunanan@pup.edu.ph', NOW()),
  ('Engr. Pedrito M. Tenerife Jr.', 'pmtenerife@pup.edu.ph', NOW()),
  ('Paul Benedict A. Serafica', 'pbaserafica@pup.edu.ph', NOW()),
  ('Christian H. Villegas', 'chvillegas@pup.edu.ph', NOW()),
  ('Amurao, Micalyne R.', 'mramurao@pup.edu.ph', NOW()),
  ('Maraya, Lorelyn F.', 'lfmaraya@pup.edu.ph', NOW()),
  ('Reyes, Vincent Paul R.', 'vprreyes@pup.edu.ph', NOW()),
  ('Coronado, Criselda P.', 'cpcoronado@pup.edu.ph', NOW()),
  ('Salac, Almoncito M.', 'amsalac@pup.edu.ph', NOW()),
  ('Galang, May M.', 'mmgalang@pup.edu.ph', NOW()),
  ('Estingor, Fernando F.', 'ffestingor@pup.edu.ph', NOW()),
  ('Estingor, Jenny Q.', 'jqestingor@pup.edu.ph', NOW()),
  ('Rosemarie O. Roque', 'rroque@pup.edu.ph', NOW()),
  ('Manolito R. Tangan Jr.', 'mrtanganjr@pup.edu.ph', NOW()),
  ('Maria Lourdes F. Rebulanan', 'mlfrebulanan@pup.edu.ph', NOW()),
  ('Joana Marie G. Bernardo', 'jmgbernardo@pup.edu.ph', NOW()),
  ('Kamille Legaspi-Torres', 'kdlegaspi@pup.edu.ph', NOW()),
  ('Lucelle Antonette S. Ramos', 'lavsotelo@pup.edu.ph', NOW()),
  ('Dr. Ryan C. Roque, CPA', 'rcroque@pup.edu.ph', NOW()),
  ('Noel A. Bergonia, CPA', 'nabergonia@pup.edu.ph', NOW()),
  ('Marietta M. Doquenia, CPA', 'mmdoquenia@pup.edu.ph', NOW()),
  ('Lyra Victoria V. Lascano, CPA', 'lvmvillareal@pup.edu.ph', NOW()),
  ('Ariel E. Serrano, CPA', 'aeserrano@pup.edu.ph', NOW()),
  ('Dr. Cherry Casuat', 'cdcasuat@pup.edu.ph', NOW()),
  ('Ibylou Bandala-Golla', 'ibgolla@pup.edu.ph', NOW()),
  ('Dr. Arvin R. De La Cruz', 'arrdelacruz@pup.edu.ph', NOW()),
  ('Engr. Pedrito M. Tenerife Jr', 'pmtenerife@pup.edu.ph', NOW()),
  ('Assoc. Prof. Gerlie C. Ogatis', 'gc.ogatis@pup.edu.ph', NOW()),
  ('Assoc. Prof. Hazel DR. Samala', 'hdrsamala@pup.edu.ph', NOW()),
  ('Engr. Orlando Delfino Tubola', 'odtubola@pup.edu.ph', NOW()),
  ('John Michael Legaspi', 'jmvlegaspi@pup.edu.ph', NOW()),
  ('Mr. Mark Joseph N. Rafal', 'mjnrafal@pup.edu.ph', NOW()),
  ('Mitch Shiela D. Rioveros', 'mssdiokno@pup.edu.ph', NOW()),
  ('Huryetha D. Marasigan', 'hdmarasigan@pup.edu.ph', NOW()),
  ('Roselyn F. Panopio', 'rpanopio@pup.edu.ph', NOW()),
  ('Bevvy Stefane Tan', 'bsetan@pup.edu.ph', NOW()),
  ('Dr. Jose Reuben Alagaran II', 'jrqalagaran@pup.edu.ph', NOW()),
  ('Dr. Ryan Pasigan Reyes', 'rpreyes@pup.edu.ph', NOW()),
  ('Melchor M. De Guzman', 'mmdeguzman@pup.edu.ph', NOW()),
  ('Joel S. Baldago', 'jsbaldago@pup.edu.ph', NOW()),
  ('Maria Hayde P. Martinez', 'mhpmartinez@pup.edu.ph', NOW()),
  ('Rafael R. Ramos', 'rrramos@pup.edu.ph', NOW()),
  ('April Mae A. Berganos', 'amaberganos@pup.edu.ph', NOW()),
  ('Jeralgie R. Castanas', 'jrcastanas@pup.edu.ph', NOW()),
  ('Eloisa Mae P. Lipio', 'emplipio@pup.edu.ph', NOW()),
  ('Marie Claire Duque-Cruz', 'mctduquecruz@pup.edu.ph', NOW()),
  ('Dr. Lincoln A. Bautista', 'labautista@pup.edu.ph', NOW()),
  ('Jenny L. Llano', 'jlllano@pup.edu.ph', NOW()),
  ('Dr. Geraldine C. Miñas', 'gcminas@pup.edu.ph', NOW()),
  ('Mr. Justin Julian Cachola', 'jjcachola@pup.edu.ph', NOW()),
  ('Agnes Sunga- Oblefias', 'amsunga@pup.edu.ph', NOW()),
  ('Dr. Joseph Reylan B. Viray', 'jrbviray@pup.edu.ph', NOW()),
  ('Mary Sarah L. Angoluan', 'mslangoluan@pup.edu.ph', NOW()),
  ('Nicky C. Cardenas', 'nccardenas@pup.edu.ph', NOW()),
  ('Stanley A. Gullab', 'sagullab@pup.edu.ph', NOW()),
  ('Prof. Marilyn F. Isip', 'mfisip@pup.edu.ph', NOW()),
  ('Asst. Prof Joanna Marie G. Bernardo', 'jmgbernardo@pup.edu.ph', NOW()),
  ('Asst. Prof. Marvin M. Espiritu', 'mmespiritu@pup.edu.ph', NOW()),
  ('Dr. Angelita M. Pagcalilawan', 'ampagcaliwagan@pup.edu.ph', NOW()),
  ('Abegail A. Malabuyoc', 'aamalabuyoc@pup.edu.ph', NOW()),
  ('Anna Marielle D. Ramos', 'amdramos@pup.edu.ph', NOW()),
  ('Ar. Gloria B. Teodoro', 'gbteodoro@pup.edu.ph', NOW()),
  ('Dr. Kriztine R. Viray', 'kr.viray@pup.edu.ph', NOW()),
  ('Engr. Armando N. Victoria Jr.', 'anvictoriajr@pup.edu.ph', NOW()),
  ('Dr. Ricky Rosales', 'rrrosales@pup.edu.ph', NOW()),
  ('Dr. Norie L. Maniego', 'nlmaniego@pup.edu.ph', NOW()),
  ('Dr. Jayson Esmasin', 'jccesmasin@pup.edu.ph', NOW()),
  ('Dr. Minerva Ferranco', 'md.ferranco@pup.edu.ph', NOW()),
  ('Dr. Joana Marie G. Bernardo', 'jmgbernardo@pup.edu.ph', NOW()),
  ('Gregorio R. Caliquia III', 'grcaliguiaiii@pup.edu.ph', NOW()),
  ('Jaymil B. Delos Reyes', 'jbdelosreyes@pup.edu.ph', NOW()),
  ('John Patrick G. Jacinto', 'jpgjacinto@pup.edu.ph', NOW()),
  ('Jairus P. Aguila', 'jpaguila@pup.edu.ph', NOW()),
  ('Ryan M. Aguinaldo', 'rmaguinaldo@pup.edu.ph', NOW()),
  ('Atty. Minami O. Iwayama', 'moiwayama@pup.edu.ph', NOW()),
  ('Dr. Dina Grace T. Magnaye', 'dgmagnaye@pup.edu.ph', NOW()),
  ('Rejeneil F. Dela Cruz', 'rfdelacruz@pup.edu.ph', NOW()),
  ('Carmelo T. Osorio Jr.', 'ctosoriojr@pup.edu.ph', NOW()),
  ('John R. Dela Cruz', 'jrdelacruz@pup.edu.ph', NOW()),
  ('Dr. Erickson E. Fajiculay', 'eefajiculay@pup.edu.ph', NOW()),
  ('Jose Clutario', 'jvclutario@pup.edu.ph', NOW()),
  ('Jo-Ann V. Magsumbol', 'javmagsumbol@pup.edu.ph', NOW()),
  ('Anna Madonna M. Arellano', 'ammarellano@pup.edu.ph', NOW()),
  ('Dr. Marife A. Acierto', 'maacierto@pup.edu.ph', NOW()),
  ('Assoc. Prof. Jonathan U. Florida', 'juflorida@pup.edu.ph', NOW()),
  ('Dr. Daryl Ace V. Cornell', 'davcornell@pup.edu.ph', NOW()),
  ('Engr. Edison E. Mojica', 'eemojica@pup.edu.ph', NOW()),
  ('Dr. Rudolf Anthony A. Lacerna', 'raalacerna@pup.edu.ph', NOW()),
  ('Dr. Nina Katreena D. Guiritan', 'nkdguiritan@pup.edu.ph', NOW()),
  ('Dr. Rodante J. Caysip Jr.', 'rjcaysipjr@pup.edu.ph', NOW()),
  ('Assoc. Prof. Jane S. Pulma', 'jspulma@pup.edu.ph', NOW()),
  ('Dr. David John D. Apigo', 'djdapigo@pup.edu.ph', NOW()),
  ('Joseph Victor D. Deseo', 'jvddeseo@pup.edu.ph', NOW()),
  ('Mary Grace I. Cruz', 'mgicruz@pup.edu.ph', NOW()),
  ('Jocelyn A. Rivera-Lutap', 'jarlutap@pup.edu.ph', NOW()),
  ('Prince Guillan D. Cruz', 'pgdcruz@pup.edu.ph', NOW()),
  ('Christopher V. Bagaconza', 'cvbagaconza@pup.edu.ph', NOW()),
  ('Christian Neil A. Ramos', 'cnaramos@pup.edu.ph', NOW()),
  ('Dr. Allan A. Calderon', 'aacalderon@pup.edu.ph', NOW()),
  ('Cyril Jes Sy Aureada', 'cjsaureada@pup.edu.ph', NOW()),
  ('Aldrin Philip C. Trance', 'aptrance@pup.edu.ph', NOW()),
  ('Joseph Reylan B. Viray', 'jrbviray@pup.edu.ph', NOW()),
  ('Jacquiline S. Tychuaco', 'jstychuaco@pup.edu.ph', NOW()),
  ('Kim Berard G. Fajardo', 'kbgfajardo@pup.edu.ph', NOW()),
  ('Dr. Kriztine Rosales-Viray', 'kr.viray@pup.edu.ph', NOW()),
  ('Damiel Joseph U. Caasi', 'djucaasi@pup.edu.ph', NOW()),
  ('Sonny M. Versoza', 'smversoza@pup.edu.ph', NOW()),
  ('Dr. Florentino D. Poso Jr.', 'fdposo@pup.edu.ph', NOW()),
  ('Mary Grace B. Mulawin', 'mgbmulawin@pup.edu.ph', NOW()),
  ('Dr. Federico Jose Lagdameo', 'fjtlagdameo@pup.edu.ph', NOW()),
  ('Yolanda T. Montances', 'ytmontances@pup.edu.ph', NOW()),
  ('Luzviminda O. Tugade', 'lo.tugade@pup.edu.ph', NOW()),
  ('Ma. Cristina Q. Trinidad', 'mcqtrinidad@pup.edu.ph', NOW()),
  ('Dr. Jayson C. Jimenez', 'jcjimenez@pup.edu.ph', NOW()),
  ('Gregorio R. Caligua, III', 'grcaliguiaiii@pup.edu.ph', NOW()),
  ('Dr. Bernice G. Mangabat', 'bgmangabat@pup.edu.ph', NOW()),
  ('Malaya Abadilla Ygot', 'maygot@pup.edu.ph', NOW()),
  ('Agnes Sunga-Oblefias', 'amsunga@pup.edu.ph', NOW()),
  ('Dr. Ernie C. Avila', 'ecavila@pup.edu.ph', NOW()),
  ('Airavie Joy DR. Austria', 'ajdraustria@pup.edu.ph', NOW()),
  ('Al Vincent A. Jabines', 'avajabines@pup.edu.ph', NOW()),
  ('Gerlie Caspe-Ogatis', 'gc.ogatis@pup.edu.ph', NOW()),
  ('Dr. Rhodora R. Julian', 'rrjulian@pup.edu.ph', NOW()),
  ('Arlene B. Canlas', 'abcanlas@pup.edu.ph', NOW()),
  ('Rowell L. Marquina', 'rlmarquina@pup.edu.ph', NOW()),
  ('Justin Julian Cachola', 'jjcachola@pup.edu.ph', NOW()),
  ('Dr. Diana Lee Tracy K. Chan', 'dltkchan@pup.edu.ph', NOW()),
  ('Engr. Julius S. Cansino', 'jscansino@pup.edu.ph', NOW()),
  ('Dr. Henry B. Prudente', 'hbprudente@pup.edu.ph', NOW()),
  ('Sarah Jean Q. Cabanig', 'sjqcabanig@pup.edu.ph', NOW()),
  ('Rhea R. Bernardino', 'rrbernardino@pup.edu.ph', NOW()),
  ('Shaina Lyra B. Macatangay', 'slbmacatangay@pup.edu.ph', NOW()),
  ('Andrew C. Hernandez', 'achernandez@pup.edu.ph', NOW()),
  ('Jacky Boy E. Atienza', 'jbeatienza@pup.edu.ph', NOW()),
  ('Francis Leo T. Mingo', 'fltmingo@pup.edu.ph', NOW()),
  ('Lincoln Bautista', 'labautista@pup.edu.ph', NOW()),
  ('Jose Alejandro Constantino L. Lara', 'jacllara@pup.edu.ph', NOW()),
  ('Paul Ryan Longhas', 'pralonghas@pup.edu.ph', NOW()),
  ('Mark L. Caay', 'mlcaay@pup.edu.ph', NOW()),
  ('Kenneth James T. Nuguid', 'kjtnuguid@pup.edu.ph', NOW()),
  ('John Patrick B. Sta. Maria', 'jpbstamaria@pup.edu.ph', NOW()),
  ('Katrina D. Elizon', 'kdelizon@pup.edu.ph', NOW()),
  ('Perlyn Mae R. Dilla', 'pmrdilla@pup.edu.ph', NOW()),
  ('Rafael A. Duterte', 'raduarte@pup.edu.ph', NOW()),
  ('Edcon Baccay', 'ebbaccay@pup.edu.ph', NOW()),
  ('Jackie Urrutia', 'jdurrutia@pup.edu.ph', NOW()),
  ('Rolan J. Malvar', 'rjmalvar@pup.edu.ph', NOW()),
  ('Dr. Jocelyn A. Rivera-Lutap', 'jarlutap@pup.edu.ph', NOW()),
  ('Dr. Ma. Junithesmer D. Rosales', 'mjdrosales@pup.edu.ph', NOW()),
  ('Angelo P. Pera', 'appera@pup.edu.ph', NOW()),
  ('Dr. Cindy F. Soliman', 'cfsoliman@pup.edu.ph', NOW()),
  ('Ruby Jean S. Medina', 'rjsmedina@pup.edu.ph', NOW()),
  ('Joshua Bernard Espeña', 'jbbespena@pup.edu.ph', NOW()),
  ('Dr. Lutzer U. Reyes', 'lureyes@pup.edu.ph', NOW()),
  ('Ivan N. Faronal', 'infaronal@pup.edu.ph', NOW()),
  ('Pamela Grace C. Muhi', 'pgcmuhi@pup.edu.ph', NOW()),
  ('Lutzer U. Reyes', 'lureyes@pup.edu.ph', NOW()),
  ('Rudolf Anthony A. Lacerna', 'raalacerna@pup.edu.ph', NOW()),
  ('Diana Lee Tracy K. Chan', 'dltkchan@pup.edu.ph', NOW()),
  ('Adam Palma', 'aapalma@pup.edu.ph', NOW()),
  ('Ronalyn Joy M. Canceran', 'rjmcanceran@pup.edu.ph', NOW()),
  ('Rayan C. Soriano', 'rcsoriano@pup.edu.ph', NOW()),
  ('Alden O. Obuyes', 'aoobuyes@pup.edu.ph', NOW()),
  ('Bryan Joseph S. Oriondo', 'bjsoriondo@pup.edu.ph', NOW()),
  ('Honeylyn R. Dela Rosa', 'hrdelarosa@pup.edu.ph', NOW()),
  ('AR/ENP. Gloria B. Teodoro', 'gbteodoro@pup.edu.ph', NOW()),
  ('Abel Pelandiana', 'alpelandiana@pup.edu.ph', NOW()),
  ('AR. Jocelyn A. Rivera Lutap', 'jarlutap@pup.edu.ph', NOW()),
  ('Dr. Louvelle S. Formentera', 'lsformentera@pup.edu.ph', NOW()),
  ('Lualhati A. Dela Cruz', 'ladelacruz@pup.edu.ph', NOW()),
  ('Gracia J. Abin', 'gjabin@pup.edu.ph', NOW()),
  ('Sharmaine P. Bañadera', 'spbanadera@pup.edu.ph', NOW()),
  ('Myra Monica B. Dela Cruz', 'mmbdelacruz@pup.edu.ph', NOW()),
  ('Shermain V. Jacob', 'svjacob@pup.edu.ph', NOW()),
  ('Dr. Elmer G. De Jose', 'egdejose@pup.edu.ph', NOW()),
  ('Dr. Ivan N. Faronal', 'infaronal@pup.edu.ph', NOW()),
  ('June Kate F. Subia', 'jkfsubia@pup.edu.ph', NOW()),
  ('Dr. Junithesmer D. Rosales', 'mjdrosales@pup.edu.ph', NOW()),
  ('Marian B. Reynales', 'mbreynales@pup.edu.ph', NOW()),
  ('Dr. Josefin D. Fajardo', 'jfajardo@pup.edu.ph', NOW()),
  ('Ronel B. De Loyola', 'rbdeloyola@pup.edu.ph', NOW()),
  ('April Mae A, Berganos', 'amaberganos@pup.edu.ph', NOW()),
  ('Cecilia Q. Nacpil', 'cqnacpil@pup.edu.ph', NOW()),
  ('Arjay B. Pineda', 'abpineda@pup.edu.ph', NOW()),
  ('Armieliza A. Dela Cruz', 'aadelacruz@pup.edu.ph', NOW()),
  ('Rafael A. Duarte', 'raduarte@pup.edu.ph', NOW()),
  ('Dr. Ana Ruby P. Gapasin', 'arpgapasin@pup.edu.ph', NOW()),
  ('Dr. Rolan J. Malvar', 'rjmalvar@pup.edu.ph', NOW()),
  ('Assoc. Prof. Marynelle L. Rosales', 'mlrosales@pup.edu.ph', NOW()),
  ('Assoc. Prof. Raquel A. Arevalo', 'raarevalo@pup.edu.ph', NOW()),
  ('Dr. Ria S. Fajilago', 'rsfajilago@pup.edu.ph', NOW()),
  ('Dir. Emy Ruth D. Gianan', 'erdgianan@pup.edu.ph', NOW()),
  ('Andres, Christopher G.', 'cgandres@pup.edu.ph', NOW()),
  ('De Jesus, Clifford Jonathan T.', 'cjtdejesus@pup.edu.ph', NOW()),
  ('De Los Santos, Charles Philip O.', 'cpodelossantos@pup.edu.ph', NOW()),
  ('Macalandag, Rea Angel B.', 'rabmacalandag@pup.edu.ph', NOW()),
  ('Padilla Edwin T.', 'ecpadilla@pup.edu.ph', NOW()),
  ('Silos, Hyacynth Rodeand Shane A.', 'hsrasilos@pup.edu.ph', NOW()),
  ('Astilla, Rodel B.', 'rbastilla@pup.edu.ph', NOW()),
  ('Gerez, Roy Mark B.', 'rmbgerez@pup.edu.ph', NOW()),
  ('Pineda, Beatrice Joyce S.', 'bjspineda@pup.edu.ph', NOW()),
  ('Aure, Lariza Nicole A.', 'lnaaure@pup.edu.ph', NOW()),
  ('Gatan, Jamaica Ann B.', 'jabgatan@pup.edu.ph', NOW()),
  ('Torralba, Kimberly D.L.S', 'kdtorralba@pup.edu.ph', NOW()),
  ('Antonio F. Enriquez Jr.', 'afenriquezjr@pup.edu.ph', NOW()),
  ('Geraldine C. Minas', 'gcminas@pup.edu.ph', NOW()),
  ('Rhizelle C. Cruz', 'rccelestial@pup.edu.ph', NOW()),
  ('Jane Claire Sacandal', 'jcssacandal@pup.edu.ph', NOW()),
  ('John Mark N. Nero', 'jmnnero@pup.edu.ph', NOW()),
  ('Alyssa Mae M. Resurreccion', 'ammresurreccion@pup.edu.ph', NOW()),
  ('Wendell Padilla', 'wmpadilla@pup.edu.ph', NOW()),
  ('Genesis S. Linga', 'gslinga@pup.edu.ph', NOW()),
  ('Michael James L. Sabado', 'mjlsabado@pup.edu.ph', NOW()),
  ('Ryan Enriquez', 'raenriquez@pup.edu.ph', NOW()),
  ('Danilo T. Rojas', 'dtrojas@pup.edu.ph', NOW()),
  ('Shin Sedenio', 'sgsedenio@pup.edu.ph', NOW()),
  ('Blesilda L. Cortez', 'blcortez@pup.edu.ph', NOW()),
  ('Zoe Bernadette Tolentino', 'zbctolentino@pup.edu.ph', NOW()),
  ('Sheryl Serrano', 'ssserrano@pup.edu.ph', NOW()),
  ('Connie SJ. Macalintal', 'csmacalintal@pup.edu.ph', NOW()),
  ('Jedidia Eunice P. Pena', 'jeppena@pup.edu.ph', NOW()),
  ('Jefferson F. Serrano', 'jfserrano@pup.edu.ph', NOW()),
  ('Federick Cecilio A. Baysa', 'fcabaysa@pup.edu.ph', NOW()),
  ('Ariston Alex Torres', 'aamtorres@pup.edu.ph', NOW()),
  ('Jay Alvin Sichon', 'jassichon@pup.edu.ph', NOW()),
  ('Heildenberg Dimarucot', 'hcdimarucot@pup.edu.ph', NOW()),
  ('Elaine Carie A. Andres', 'ecaandres@pup.edu.ph', NOW()),
  ('Federico R. Arzadon, Jr.', 'frarzadonjr@pup.edu.ph', NOW()),
  ('Joel Baldago', 'jsbaldago@pup.edu.ph', NOW()),
  ('Christian Paul B. Trance', 'cpbtrance@pup.edu.ph', NOW()),
  ('Jose Andres Serrano', 'jacserranoiii@pup.edu.ph', NOW()),
  ('Nino Inocencio A. Santos', 'niasantos@pup.edu.ph', NOW()),
  ('Mary Ann G. Quinante', 'magquinante@pup.edu.ph', NOW()),
  ('Janvier B. Mantala', 'jbmantala@pup.edu.ph', NOW()),
  ('Ronald Alejo M. Guiriba', 'ramguiriba@pup.edu.ph', NOW()),
  ('Russel I. Tropa', 'ritropa@pup.edu.ph', NOW()),
  ('Juanito Dela Cruz', 'jcdelacruz@pup.edu.ph', NOW()),
  ('Camille Cayron', 'cscayron@pup.edu.ph', NOW()),
  ('Cris Mathew L. Obias', 'cmlobias@pup.edu.ph', NOW()),
  ('Elijah Paul Delmo', 'epbdelmo@pup.edu.ph', NOW()),
  ('Ara Diether Ley Y. De Chavez', 'adlydechavez@pup.edu.ph', NOW()),
  ('Maria Hiedi P. Martinez', 'mhpmartinez@pup.edu.ph', NOW()),
  ('Liza D. Camarador', 'ldcamarador@pup.edu.ph', NOW())
ON CONFLICT (faculty_name) DO UPDATE SET
  email = EXCLUDED.email,
  updated_at = NOW();